# -*- coding: utf-8 -*-
"""project2_all_gps_satellite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bBLrk7dqecC5d8x45xj9oOTAH-sHEyi0

=============================================================================
🛰️ Project 2 — All GPS Satellites Analysis
=============================================================================
 Author   : Hakim El Azzouzi
 Degree   : MSc Global Navigation Satellite Systems
            Mohammed First University, Oujda, Morocco
 Email    : elazzouzihakim10@gmail.com
 LinkedIn : https://linkedin.com/in/Hakim-El-Azzouzi
 Location : Luxembourg 🇱🇺
-----------------------------------------------------------------------------
 Station  : AUCK00NZL  —  Auckland, New Zealand  (GeoNet / LINZ Network)
 File     : AUCK00NZL_R_20260010000_01D_30S_MO.rnx
 Receiver : TRIMBLE ALLOY
 Antenna  : TRM115000.00
 Format   : RINEX 3.05  |  Mixed Constellations  |  30-second sampling
 Date     : 2026-01-01  (Day-of-Year 001)
-----------------------------------------------------------------------------
 Description
 -----------
While Project 1 focused on a **single GPS satellite**, this project looks at
the **entire GPS constellation** tracked over 24 hours from the AUCK00NZL station.
At any given moment, a receiver in Auckland can see between 6 and 12 GPS satellites simultaneously — this is what makes GNSS positioning possible. We visualise the full picture:

- **All GPS pseudorange arcs** overlaid on the same plot — each curve is one satellite
- **Full SNR heatmap** — one row per satellite, colour = signal strength over time
-----------------------------------------------------------------------------
 **About the projects**
 ----------------------
# Step1: Install & Import Libraries
# Step2: Load the RINEX File
# Step3: Identifying All GPS Satellites
# Step4: Plot 1: All GPS Pseudorange Arcs
# Step5: Plot 2: Full GPS SNR Heatmap (Satellite Availability)
# Step6: Satellite Availability Statistics
=============================================================================
"""

pip install --upgrade georinex

# ──────────────────────────────────────────────────────────
# Step 1 — Install & Import Libraries
# ──────────────────────────────────────────────────────────
# Install georinex if not already installed
# Uncomment the line below if you are running this for the first time:
# !pip install --upgrade georinex

import georinex as gr
import xarray as xr
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.colors import LinearSegmentedColormap
import warnings

warnings.filterwarnings('ignore')  # suppress xarray FutureWarnings during load

# Global plot style (dark GNSS theme)
plt.rcParams.update({
    'figure.dpi': 120,
})

print('✅ All libraries loaded successfully')
print(f'   georinex version : {gr.__version__}')
print(f'   xarray version   : {xr.__version__}')

# ─────────────────────────────────────────────────────────────────
# Step 2 — Load the RINEX File
# ─────────────────────────────────────────────────────────────────
# RINEX FILE PATH HERE
obs_path = "/AUCK00NZL_R_20260010000_01D_30S_MO.rnx"  # ← change this path
# Read the file header first (fast — no data loaded yet)
print("📋 FILE HEADER")
print("=" * 60)
header = gr.rinexheader(obs_path)

for key, value in header.items():
    print(f"{key:<25}: {value}")

print()

# Load all observation data (interval=30 means keep 30-sec rate)

print("⏳ Loading observation data (this may take 1–2 minutes)...")
obs = gr.load(obs_path, interval=30)
print()
print("✅ Data loaded!")
print(obs)

# ─────────────────────────────────────────────────────────────────
# Step 3 — Identifying All GPS Satellites
# ─────────────────────────────────────────────────────────────────
# Extract all GPS satellites from the file
all_sv = obs.sv.values

# Sort satellites by PRN number for clean display
gps_sats = sorted([s for s in all_sv if s.startswith('G')])

print(f"🛰️  GPS satellites found in file: {len(gps_sats)}")
print("   " + "  ".join(gps_sats))
print()

# ─────────────────────────────────────────────────────────────────
# Determine which pseudorange observable to use
# C1C is the standard L1 C/A code pseudorange for GPS
# C1X is an alternative for some receivers
# ─────────────────────────────────────────────────────────────────
if 'C1C' in obs.data_vars:
    pr_code = 'C1C'
elif 'C1X' in obs.data_vars:
    pr_code = 'C1X'
else:
    raise ValueError("Neither C1C nor C1X pseudorange found in this RINEX file.")

if 'S1C' in obs.data_vars:
    snr_code = 'S1C'
elif 'S1X' in obs.data_vars:
    snr_code = 'S1X'
else:
    raise ValueError("Neither S1C nor S1X SNR observable found in this RINEX file.")

print(f"✅ Using pseudorange observable : {pr_code}")
print(f"✅ Using SNR observable         : {snr_code}")
print()

# Quick data availability summary

total_epochs = obs.dims['time']
print(f"📊 Total epochs in file: {total_epochs}  (= {total_epochs * 30 / 3600:.0f} hours at 30-sec rate)")
print()
print(f"{'Satellite':<12} {'Valid Epochs':>14} {'Coverage %':>12} {'Mean SNR':>12}")
print("-" * 52)

for sat in gps_sats:
    try:
        valid = obs[pr_code].sel(sv=sat).to_series().notna().sum()
        coverage = valid / total_epochs * 100
        snr_mean = obs[snr_code].sel(sv=sat).to_series().dropna().mean()
        snr_str = f"{snr_mean:.1f} dB-Hz" if not np.isnan(snr_mean) else "N/A"
        print(f"  {sat:<10} {valid:>14} {coverage:>11.1f}% {snr_str:>14}")
    except Exception:
        print(f"  {sat:<10} {'Error':>14}")

# ─────────────────────────────────────────────
# Step 4 — Plot 1: All GPS Pseudorange Arcs
# ─────────────────────────────────────────────
# Build a colour palette for all GPS satellites
# Using a qualitative colormap so satellites are easily distinguishable

n_sats = len(gps_sats)
palette = plt.cm.tab20(np.linspace(0, 1, n_sats))
sat_colors = {sat: palette[i] for i, sat in enumerate(gps_sats)}

# Figure

fig, ax = plt.subplots(figsize=(16, 7), facecolor="#0d1117")
ax.set_facecolor("#111827")

ax.set_title(
    f'All GPS Satellites — Pseudorange ({pr_code}) | AUCK00NZL | 2026-01-01\n'
    f'Each curve is one satellite | {n_sats} satellites tracked over 24 hours',
    fontsize=13, fontweight='bold', color="#ffffff"
)

# Plot one arc per GPS satellite

plotted = []

for sat in gps_sats:
    try:
        pr = obs[pr_code].sel(sv=sat).to_series().dropna()

        if len(pr) < 5:   # skip satellites with almost no data
            continue

        ax.plot(
            pr.index,
            pr.values / 1e6,   # convert metres → million metres (Mm)
            lw=1.4,
            alpha=0.85,
            color=sat_colors[sat],
            label=sat
        )
        plotted.append(sat)

    except Exception as e:
        print(f"   Skipped {sat}: {e}")

# Axes formatting

ax.set_ylabel('Pseudorange [Mm = million metres]', fontsize=11, color="#aaaaaa")
ax.set_xlabel('UTC Time (HH:MM)', fontsize=11, color="#aaaaaa")

ax.tick_params(colors="#aaaaaa")
ax.grid(True, color="#222222", linewidth=0.5)

for spine in ax.spines.values():
    spine.set_edgecolor("#333333")

# Time axis
ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

# Legend (compact, 4 columns)
legend = ax.legend(
    ncol=4, fontsize=8,
    loc='upper right',
    framealpha=0.3,
    facecolor="#1a1a2e",
    edgecolor="#444444"
)
for text in legend.get_texts():
    text.set_color("white")

plt.tight_layout()
plt.savefig('plot1_all_gps_pseudorange.png', dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print(f'✅ Plot saved: plot1_all_gps_pseudorange.png')
print(f'   Satellites plotted: {len(plotted)}')
print()
print('💡 Interpretation:')
print('   • Each arc = one satellite rising, reaching peak elevation, then setting.')
print('   • Minimum of each arc = satellite at highest elevation (closest to receiver).')
print('   • Gaps in a curve = signal interruption (obstacle, low elevation, multipath).')
print('   • Satellites near the horizon produce larger pseudoranges (farther away).')

# ──────────────────────────────────────────────────────────────
# Step 5 — Plot 2: Full GPS SNR Heatmap (Satellite Availability)
# ──────────────────────────────────────────────────────────────
# Build SNR matrix: rows = satellites, columns = time epochs

# Select GPS satellites and load their SNR
snr_gps = obs[snr_code].sel(sv=gps_sats)

# Convert to pandas DataFrame: rows = time, columns = satellites
snr_df = snr_gps.to_pandas()

# Transpose: rows = satellites, columns = time (for heatmap)
snr_matrix = snr_df[gps_sats].T.values

# Replace NaN (satellite not visible) with a sentinel value
# We use 10 dB-Hz so it shows as dark on the colormap
snr_matrix_display = np.where(np.isnan(snr_matrix), 10, snr_matrix)

print(f"✅ SNR matrix built: {snr_matrix.shape[0]} satellites × {snr_matrix.shape[1]} epochs")

# Custom GNSS colormap

gnss_cmap = LinearSegmentedColormap.from_list(
    "gnss_snr",
    [
        "#0d1117",  # background / no data
        "#1a0533",  # deep purple (very weak signal)
        "#2c3e8c",  # blue (low signal)
        "#0099cc",  # cyan (moderate signal)
        "#00e676",  # green (good signal)
        "#ffeb3b",  # yellow (strong signal)
        "#ff6f00",  # orange (excellent / saturation)
    ],
    N=256
)

# Figure

fig, ax = plt.subplots(figsize=(16, 8), facecolor="#0d1117")
ax.set_facecolor("#0d1117")

im = ax.pcolormesh(
    snr_df.index,         # x-axis: time
    range(len(gps_sats)), # y-axis: satellite index
    snr_matrix_display,   # colour data
    cmap=gnss_cmap,
    vmin=15,
    vmax=55,
    shading='auto'
)

# Colorbar

cbar = plt.colorbar(im, ax=ax, pad=0.01)
cbar.set_label('SNR [dB-Hz]', color="#e0e0e0", fontsize=11)
cbar.ax.yaxis.set_tick_params(color="#aaaaaa")
plt.setp(cbar.ax.get_yticklabels(), color="#aaaaaa")

# Add quality reference labels to colorbar
cbar.ax.axhline(25, color='#F44336', lw=1.5, linestyle='--')
cbar.ax.axhline(35, color='#4CAF50', lw=1.5, linestyle='--')

# Y axis — satellite PRN labels

ax.set_yticks(range(len(gps_sats)))
ax.set_yticklabels(gps_sats, fontsize=9, color="#e0e0e0")

# Titles and labels

ax.set_title(
    f'GPS Signal-to-Noise Ratio Heatmap — All {len(gps_sats)} Satellites\n'
    'AUCK00NZL | Auckland, New Zealand | 2026-01-01 | 30-sec sampling',
    fontsize=13, fontweight='bold', color="#ffffff"
)

ax.set_xlabel('UTC Time (HH:MM)', fontsize=11, color="#e0e0e0")
ax.set_ylabel('GPS Satellite (PRN)', fontsize=11, color="#e0e0e0")

# Time axis formatting

ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")
ax.tick_params(axis='y', colors="#aaaaaa")

for spine in ax.spines.values():
    spine.set_edgecolor("#333333")

plt.tight_layout()
plt.savefig('plot2_gps_snr_heatmap.png', dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print('✅ Plot saved: plot2_gps_snr_heatmap.png')
print()
print('💡 Interpretation:')
print('   • Each ROW = one GPS satellite\'s tracking arc through the day')
print('   • Dark (black/blue) = satellite below horizon or very weak signal')
print('   • Green = good tracking conditions (SNR > 35 dB-Hz)')
print('   • Yellow/Orange = excellent signal (satellite high in the sky)')
print('   • Look for columns where MANY rows are lit up = many sats visible simultaneously')

# ──────────────────────────────────────────────────────────────
# Step 6 — Satellite Availability Statistics
# ──────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────
# Count how many GPS satellites are visible at each epoch
# ─────────────────────────────────────────────

# Count non-NaN pseudorange values across GPS satellites for each time step
gps_count = obs[pr_code].sel(sv=gps_sats).count(dim='sv').to_series()

# ─────────────────────────────────────────────
# Plot
# ─────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(14, 4), facecolor="#0d1117")
ax.set_facecolor("#111827")

ax.plot(gps_count.index, gps_count.values, color="#2196F3", lw=1.5, label='GPS satellites tracked')
ax.fill_between(gps_count.index, gps_count.values, color="#2196F3", alpha=0.2)

# Minimum needed for positioning
ax.axhline(4, color="#F44336", ls='--', lw=1.2, label='Min for positioning (4 sats)')
ax.axhline(gps_count.mean(), color="#FFEB3B", ls='--', lw=1.2, label=f'Mean: {gps_count.mean():.1f} sats')

ax.set_ylabel('GPS Satellites Tracked', color="#aaaaaa", fontsize=11)
ax.set_xlabel('UTC Time (HH:MM)', color="#aaaaaa", fontsize=11)
ax.set_title(
    'GPS Satellite Availability Over 24 Hours | AUCK00NZL | 2026-01-01',
    fontsize=12, fontweight='bold', color="#ffffff"
)

ax.set_ylim(0, n_sats + 2)
ax.tick_params(colors="#aaaaaa")
ax.grid(True, color="#222222", linewidth=0.5)

for spine in ax.spines.values():
    spine.set_edgecolor("#333333")

ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))
ax.xaxis.set_major_locator(mdates.HourLocator(interval=2))
plt.xticks(rotation=30, color="#aaaaaa")

legend = ax.legend(fontsize=9, framealpha=0.3, facecolor="#1a1a2e", edgecolor="#444444")
for text in legend.get_texts():
    text.set_color("white")

plt.tight_layout()
plt.savefig('plot3_gps_availability.png', dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

# ─────────────────────────────────────────────
# Statistics
# ─────────────────────────────────────────────
print(f'📊 GPS Satellite Availability Statistics:')
print(f'   Total GPS satellites in file  : {len(gps_sats)}')
print(f'   Mean sats tracked per epoch   : {gps_count.mean():.1f}')
print(f'   Max sats tracked (best epoch) : {gps_count.max()}')
print(f'   Min sats tracked (worst epoch): {gps_count.min()}')
print(f'   Epochs with ≥ 4 GPS sats      : {(gps_count >= 4).sum()} / {len(gps_count)} ({(gps_count >= 4).mean()*100:.1f}%)')

